"""empty message

Revision ID: 230a9177cdd1
Revises: 8e8ce1771997
Create Date: 2023-08-15 07:54:44.860560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230a9177cdd1'
down_revision = '8e8ce1771997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'admin')
    # ### end Alembic commands ###
