"""empty message

Revision ID: 7d85b698788f
Revises: ef8a6bcfecc6
Create Date: 2023-08-15 07:21:42.587752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d85b698788f'
down_revision = 'ef8a6bcfecc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###
