"""empty message

Revision ID: ef8a6bcfecc6
Revises: 71c4857f3749
Create Date: 2023-08-14 19:42:15.007635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8a6bcfecc6'
down_revision = '71c4857f3749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_name'), 'user', ['name'])
    op.create_unique_constraint(op.f('uq_user_uuid'), 'user', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_uuid'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_name'), 'user', type_='unique')
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
